Twirl as external script

diff --git a/slay b/slay
--- a/slay
+++ b/slay
@@ -3,6 +3,7 @@
 ###############################################################################
 # ERROR: Let the user know if the script fails
 ###############################################################################
+# https://www.linuxjournal.com/content/bash-trap-command FOLLOW UP ON THIS
 
 trap 'ret=$?; test $ret -ne 0 && printf "\n   \e[31m\033[0m  Formation failed  \e[31m\033[0m\n" >&2; exit $ret' EXIT
 
@@ -12,11 +13,22 @@ set -e
 # TWIRL: Check for required functions file
 ###############################################################################
 
-if [ -e twirl ]; then
-	cd "$(dirname "${BASH_SOURCE[0]}")" \
-		&& . "twirl"
+# if [ -e twirl ]; then
+# 	cd "$(dirname "${BASH_SOURCE[0]}")" \
+# 		&& . "twirl"
+# else
+# 	printf "\n ⚠️  ./twirl not found  💃🏾 First, you need to twirl on your haters\n"
+# 	exit 1
+# fi
+
+# Get twirl
+eval "$(curl -s https://raw.githubusercontent.com/kellenproctor/foundation/main/twirl)"
+
+if [ -v e_lemon_ated ]; then
+	printf "\n ./twirl found, 💃🏾 let's go!!\n"
 else
 	printf "\n ⚠️  ./twirl not found  💃🏾 First, you need to twirl on your haters\n"
+	printf "\n Required functions file missing, please edit the script to get twirl\n"
 	exit 1
 fi
 
